# Generated by Django 4.0.4 on 2022-06-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_create_time_movie_director_movie_update_time_and_more'),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='create_time',
            field=models.TimeField(auto_now=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='male', max_length=6, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(to='movies.movie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='update_time',
            field=models.TimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
