# Generated by Django 4.0.4 on 2022-06-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_create_time_actor_gender_actor_movies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
    ]
