# Generated by Django 4.0.4 on 2022-06-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='movie')),
                ('year', models.IntegerField(verbose_name='publish year')),
                ('actors', models.ManyToManyField(to='actors.actor')),
            ],
        ),
    ]
